// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebScraper.Infrastructure.Persistene;

#nullable disable

namespace WebScraper.Infrastructure.Migrations
{
    [DbContext(typeof(WebScraperDbContext))]
    [Migration("20240828224309_Initial Create")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("WebScraper.Domain.Models.WebSearch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SearchExpression")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SearchProvider")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("WebSearches");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2024, 8, 20, 23, 43, 9, 797, DateTimeKind.Local).AddTicks(5874),
                            SearchExpression = "land registry search",
                            SearchProvider = "Google"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2024, 8, 20, 23, 43, 9, 797, DateTimeKind.Local).AddTicks(5929),
                            SearchExpression = "InfoTrack",
                            SearchProvider = "Google"
                        });
                });

            modelBuilder.Entity("WebScraper.Domain.Models.WebSearchResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rankings")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WebSearchId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WebSearchId");

                    b.ToTable("WebSearchResults");

                    b.HasData(
                        new
                        {
                            Id = new Guid("60fb4158-6289-4759-b6b3-a455eb8974fd"),
                            CreatedAt = new DateTime(2024, 8, 28, 23, 43, 9, 797, DateTimeKind.Local).AddTicks(6081),
                            Rankings = "1, 8, 16, 32",
                            Url = "https://www.google.co.uk/search?num=100&q=land+registry+search",
                            WebSearchId = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("9b6ea5b4-dae4-46e7-bdaf-a55573740ab4"),
                            CreatedAt = new DateTime(2024, 8, 27, 23, 43, 9, 797, DateTimeKind.Local).AddTicks(6085),
                            Rankings = "1, 4, 16, 47, 68",
                            Url = "https://www.google.co.uk/search?num=100&q=land+registry+search",
                            WebSearchId = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("155727c9-4c45-403a-bbcd-aefff7ad7322"),
                            CreatedAt = new DateTime(2024, 8, 26, 23, 43, 9, 797, DateTimeKind.Local).AddTicks(6088),
                            Rankings = "3, 10, 16, 47",
                            Url = "https://www.google.co.uk/search?num=100&q=land+registry+search",
                            WebSearchId = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("e85ed73a-a272-404e-b52f-3a8d0b5518cd"),
                            CreatedAt = new DateTime(2024, 8, 25, 23, 43, 9, 797, DateTimeKind.Local).AddTicks(6102),
                            Rankings = "2, 7, 20, 60, 89",
                            Url = "https://www.google.co.uk/search?num=100&q=land+registry+search",
                            WebSearchId = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("40e3845f-a97a-4690-859e-73690ba1eccd"),
                            CreatedAt = new DateTime(2024, 8, 24, 23, 43, 9, 797, DateTimeKind.Local).AddTicks(6105),
                            Rankings = "4, 8, 16, 32",
                            Url = "https://www.google.co.uk/search?num=100&q=land+registry+search",
                            WebSearchId = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("76c47b4d-f878-4800-a17d-099cc3ba01a0"),
                            CreatedAt = new DateTime(2024, 8, 23, 23, 43, 9, 797, DateTimeKind.Local).AddTicks(6108),
                            Rankings = "1, 8, 20, 32",
                            Url = "https://www.google.co.uk/search?num=100&q=land+registry+search",
                            WebSearchId = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("5b55026f-eaf1-46a9-9408-25a21b7eafad"),
                            CreatedAt = new DateTime(2024, 8, 28, 23, 43, 9, 797, DateTimeKind.Local).AddTicks(6111),
                            Rankings = "20, 24, 42, 80, 87, 99",
                            Url = "https://www.google.co.uk/search?num=100&q=land+registry+search",
                            WebSearchId = new Guid("00000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("84ebfc91-14dd-457b-aee4-fbacfbeca274"),
                            CreatedAt = new DateTime(2024, 8, 27, 23, 43, 9, 797, DateTimeKind.Local).AddTicks(6113),
                            Rankings = "23, 34, 67",
                            Url = "https://www.google.co.uk/search?num=100&q=land+registry+search",
                            WebSearchId = new Guid("00000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("564f0747-02e9-462e-8eb7-cdef43cb9128"),
                            CreatedAt = new DateTime(2024, 8, 26, 23, 43, 9, 797, DateTimeKind.Local).AddTicks(6116),
                            Rankings = "16, 26, 42, 60",
                            Url = "https://www.google.co.uk/search?num=100&q=land+registry+search",
                            WebSearchId = new Guid("00000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("c001922e-9ea1-4d78-8433-f7ac5ded15fb"),
                            CreatedAt = new DateTime(2024, 8, 25, 23, 43, 9, 797, DateTimeKind.Local).AddTicks(6119),
                            Rankings = "10, 18, 37, 67, 90, 98",
                            Url = "https://www.google.co.uk/search?num=100&q=land+registry+search",
                            WebSearchId = new Guid("00000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("10033b28-2d49-4fa7-9c9d-a9e6b1928606"),
                            CreatedAt = new DateTime(2024, 8, 24, 23, 43, 9, 797, DateTimeKind.Local).AddTicks(6121),
                            Rankings = "12, 30, 40, 48, 52, 66, 80",
                            Url = "https://www.google.co.uk/search?num=100&q=land+registry+search",
                            WebSearchId = new Guid("00000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("bdf46453-279c-4fb4-80b1-ba50a00502db"),
                            CreatedAt = new DateTime(2024, 8, 23, 23, 43, 9, 797, DateTimeKind.Local).AddTicks(6125),
                            Rankings = "1, 8, 18, 20, 40, 60, 82",
                            Url = "https://www.google.co.uk/search?num=100&q=land+registry+search",
                            WebSearchId = new Guid("00000000-0000-0000-0000-000000000002")
                        });
                });

            modelBuilder.Entity("WebScraper.Domain.Models.WebSearchResult", b =>
                {
                    b.HasOne("WebScraper.Domain.Models.WebSearch", null)
                        .WithMany("WebSearchResults")
                        .HasForeignKey("WebSearchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebScraper.Domain.Models.WebSearch", b =>
                {
                    b.Navigation("WebSearchResults");
                });
#pragma warning restore 612, 618
        }
    }
}
